import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TimezoneProvider } from "@/contexts/TimezoneContext";
import { AuthProvider } from "@/components/auth/AuthContext";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SLV",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <TimezoneProvider>
            {children}
            {/* Global toaster for app-wide notifications */}
            <Toaster position="top-right" richColors expand={false} />
          </TimezoneProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
